scripts: Reenable some noisy dtc warnings
DTBO generation changes in AOSP result in errors like:
    FATAL ERROR: Unrecognized check name "gpios_property"
    FATAL ERROR: Unrecognized check name "interrupts_property"

This commit reverts 58f144f9f8ea587973176a9cf3dff5ef4c019521.
Signed-off-by: Anirudh Gupta <anirudhgupta109@aosip.dev>